//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPGA_DNAProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal DefaultFPGAInCount {
            get {
                return ((decimal)(this["DefaultFPGAInCount"]));
            }
            set {
                this["DefaultFPGAInCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal DefaultFPGAOutCount {
            get {
                return ((decimal)(this["DefaultFPGAOutCount"]));
            }
            set {
                this["DefaultFPGAOutCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal DefaultInitalPopulation {
            get {
                return ((decimal)(this["DefaultInitalPopulation"]));
            }
            set {
                this["DefaultInitalPopulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public decimal DefaultFPGASquareSize {
            get {
                return ((decimal)(this["DefaultFPGASquareSize"]));
            }
            set {
                this["DefaultFPGASquareSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\[__NewGuid__]")]
        public string DefaultOutputDir {
            get {
                return ((string)(this["DefaultOutputDir"]));
            }
            set {
                this["DefaultOutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultShowFitnessGraph {
            get {
                return ((bool)(this["DefaultShowFitnessGraph"]));
            }
            set {
                this["DefaultShowFitnessGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultGeneticSwap {
            get {
                return ((int)(this["DefaultGeneticSwap"]));
            }
            set {
                this["DefaultGeneticSwap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultGeneticMutation {
            get {
                return ((int)(this["DefaultGeneticMutation"]));
            }
            set {
                this["DefaultGeneticMutation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal DefaultGeneticMutationN {
            get {
                return ((decimal)(this["DefaultGeneticMutationN"]));
            }
            set {
                this["DefaultGeneticMutationN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultResumeToggle {
            get {
                return ((bool)(this["DefaultResumeToggle"]));
            }
            set {
                this["DefaultResumeToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultCullHerd {
            get {
                return ((bool)(this["DefaultCullHerd"]));
            }
            set {
                this["DefaultCullHerd"] = value;
            }
        }
    }
}
